input {
  beats {
    port => 5044
  }
}

filter {
  # Optional: clean fields or rename if needed
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}